CFLAGS=-O3 -march=native -std=c++17 -pedantic -Wall -Wextra
all: main.cpp random_char_file.cpp random_word_file.cpp
	g++ $(CFLAGS) -o prog main.cpp
	g++ $(CFLAGS) -o random_char_file random_char_file.cpp
	g++ $(CFLAGS) -o random_word_file random_word_file.cpp



